### ISSUE TITLE
Editor crashed in preview 

### ISSUE THREAD

**Issue by MariusStenbakk** [creativeorange/craft-article#12]
Hello, 

The editor crashes when i'm using the preview function in craft. At entering the preview mode the arx-editor-frame iframe only return a blank document in the DOM. This stays even after leaving preview. Trying to add content with the '+' button only returns: 

`article-editor.js?key=##################:955 Uncaught TypeError: Cannot read properties of null (reading 'pageYOffset')`

**Comment by erlendsr** [comment]
Experiencing the same problem on two separate installs, one old project and one brand new.

**Comment by dejury** [comment]
Thanks for reporting the issue! I will dive into this error and make sure to fix this!

**Comment by dejury** [comment]
Fixed in the next release.
