### ISSUE TITLE
[Question] GraphQL support

### ISSUE THREAD

**Issue by lukasIO** [creativeorange/craft-article#13]
Hi, 

this looks very interesting, I was wondering if you are planning to add GraphQL support for it?

**Comment by dejury** [comment]
Hi @lukasIO !

Great that you are looking into this plugin :)
Can you please specify me with a use case you would like to see in combination with GraphQL?

**Comment by dejury** [comment]
Since there is no reply since the end of march, I'm closing this issue. The article plugin supports the GraphQL functionality, at least for retrieving content. If there are more functionalities needed, please let me know!
