### ISSUE TITLE
Some things

### ISSUE THREAD

**Issue by wmdhosting** [creativeorange/craft-article#15]
Any plans..  to add this by default.. 
I think this will move people to use it more..

1. Snipets  https://imperavi.com/article/examples/blocks/snippets/
2. Templates https://imperavi.com/article/examples/misc/templates/
3. Cards https://imperavi.com/article/examples/frameworks/bootstrap-cards/
4.  Carousel https://imperavi.com/article/examples/frameworks/bootstrap-carousel/
5. Make a button  https://imperavi.com/article/plugins/makebutton/

**Comment by dejury** [comment]
Hi @wmdhosting! Thanks for submitting new ideas for this Craft Plugin.

By default this should already be possible by using custom configuration, as documented here:
https://docs.creativeorange.nl/craft-article/guide/customize.html#custom-article-editor-configuration

I hope this will help.

**Comment by wmdhosting** [comment]
OK thx. have seen.. 

Testing now. and still getting some issue..

when i add it first time, all works ok..  
Then i save entry and come back .. and cant do anything. 
![Snag_10ee8cb6](https://user-images.githubusercontent.com/76176291/161033898-c1f9bb04-259d-49d8-a90c-499be5bb72be.png)
-------------------------------

After entry save..    or preview.. 
![Snag_10eefc49](https://user-images.githubusercontent.com/76176291/161033988-3dcc570b-5d7c-47b1-8465-aff39cde0ad8.png)

![Snag_10ef1520](https://user-images.githubusercontent.com/76176291/161034054-5b2074c3-6ace-4bb3-b6ea-8ec85d4ef1d1.png)

**Comment by dejury** [comment]
Did you already update the plugin to version 1.1 which was released yesterday?
If you did and still getting that error, can you please check if there are any error in your console?

**Comment by wmdhosting** [comment]
yes.. 

![Snag_113b1dd9](https://user-images.githubusercontent.com/76176291/161047846-21512959-0ae2-4aec-bf81-61a518dede62.png)

**Comment by wmdhosting** [comment]
I made custom boostrap  config..  i will send you for docs if you want after i finish all tweaks. 
so its easier for other people...

Here is how are things now..

**1. Standalone field . all work ok.**. 
**2. Inside matrix..   All work now ok.. in preview too**  
but after i save entry and go to edit again i get like this.. 

![Snag_6f6eea](https://user-images.githubusercontent.com/76176291/161370067-1ad1af60-9db8-47dc-90b8-f7998d60dc23.png)

Then i turn preview ON... field activated again ALL OK::  and back from preview all OK. field is activated ..
But after save it get like that above.

i found two more things.. 
**When much content .. toolbar not visible.. 100%**
![Snag_7218bd](https://user-images.githubusercontent.com/76176291/161370161-20e28581-21b1-4383-9ff3-77398893a313.png)

Slide in window..   not showing.. 
![Snag_733bb1](https://user-images.githubusercontent.com/76176291/161370198-274e10b2-7b6e-4068-870e-df1aaaefdd76.png)

**Comment by dejury** [comment]
Thanks for your feedback, this really helps us!
I will work on this issue soon, keep you updated!

Any content for the documentation is more then welcome  👍🏻

**Comment by wmdhosting** [comment]
Just update few more things.. 
![Snag_1ad01581](https://user-images.githubusercontent.com/76176291/162167025-2307ea1b-10f5-464d-9dc1-daece7d0d934.png)

**1. I changed that CP CSS plugin..** 
`body.ltr .meta>.field>.input>.select select {background: white;padding-left: 7px;}
body.ltr .meta>.field>.input>.select:after {right: 7px;}
.input .arx-path a.arx-path-item span {color: #008CCC;}
.input .arx-path a.arx-path-item.active span {color: rgba(0,11,29,.6);}
.arx-popup-stack.arx-popup-stack-addbar .arx-popup-item-container .arx-popup-item-icon {color: #008CCC;}

**2.  Native image field  / replace image / add multiple images..** 

![Snag_1ad4dbea](https://user-images.githubusercontent.com/76176291/162168093-43cdd9ec-717b-48d5-9089-702ac2b6d5fa.png)

**3.  Image style**  

![Snag_1ad55ca4](https://user-images.githubusercontent.com/76176291/162168223-b7f6737d-9e49-4128-b66f-090dd3695dc6.png)

**4. Cell   Icons not well places. beter if posiblel on control bar too**
![Snag_1ad65888](https://user-images.githubusercontent.com/76176291/162168435-b8a6a413-5b4b-459e-af38-ee5e7d323435.png)

**5. Style select option ..**

![Snag_1ad6e8c2](https://user-images.githubusercontent.com/76176291/162168546-e00f32c7-a8cd-4b13-ab35-f6b887a13baa.png)
![Snag_1ad7a098](https://user-images.githubusercontent.com/76176291/162168719-7bf11046-790b-4495-95e3-2680ba7d2aac.png)

Spent quite some time on carousel plugin..  but dont work withou image field.. 
Have soem more tweaks.  then will send you final CSS and info

**Comment by dejury** [comment]
I can't reproduce your issue in the Content Matrix. My fields are working okay over there!
Could you try it again? I just released v2.0.0-beta.1 for compatibility with CraftCMS 4, the issue is not reproducable in that version too.

**Comment by wmdhosting** [comment]
Still same. 

1. After adding all OK:. 
2. Preview all OK
3. Back from preview OK:. 

But when i save..   or just now tryed to save.., and was just page relaod without save 
as i didnt filled some field in other block.. 

ANd have that issue  . .here is error i see aafter that... if helps..
![Snag_bde20dd](https://user-images.githubusercontent.com/76176291/162966420-12daef5e-9f9d-45a2-bbf3-dc25c314d26d.png)

**Comment by dejury** [comment]
I am still unable to reproduce this issue, maybe i'm not doing the same you are doing.

Is it possible to generate a screencast for me how to reproduce this? Maybe this will help me.

**Comment by wmdhosting** [comment]
OK will send you soon..

**Comment by wmdhosting** [comment]
https://user-images.githubusercontent.com/76176291/165730882-c887b415-1ab4-405c-8d47-3cee2dda780e.mp4

**Comment by dejury** [comment]
Hi there,

Thanks for the screencast, really helped me!
I released a new version for CraftCMS 3 (v1.1.1) & a new version for CraftCMS 4 (v2.0.1) which should fix this issue :)

**Comment by wmdhosting** [comment]
Much better on Craft 3, still issue after save entry..and edit.. 
 but when i turn preview its OK. and back.. 
 
ITs OK.. soon i will upgrade to CRAFT 4 and let you know.. :)

Thx

**Comment by dejury** [comment]
@wmdhosting Can you please create a new issue for that specific issue and provide me with a screencast? This way we can keep track of all seperate bugs. Thanks for your help so far :)

**Comment by wmdhosting** [comment]
will do after CRAFT 4 upgrade.. if still there..
