### ISSUE TITLE
Craftarticle.js

### ISSUE THREAD

**Issue by wmdhosting** [creativeorange/craft-article#21]
![Snag_461e80](https://user-images.githubusercontent.com/76176291/198632045-df20cf59-767d-424e-a96b-f27ef5a2ee31.png)

just upgraded to 4, all work OK. :)    just getting this..  
Any idea what can be..

**Comment by wmdhosting** [comment]
i have issue. in matrix.  when i save..  entry i get..back in  gray blocked editor.. 
![Snag_1186fd4f](https://user-images.githubusercontent.com/76176291/200884214-2272d5d5-c4e7-4fe4-ba73-4de60bcd8df7.png)

And still this issue above  on frontend.. 

Any help..

**Comment by wmdhosting** [comment]
Do you still activly developing this plugin..

**Comment by wmdhosting** [comment]
Hello

If you dont plan to work on plugin anymore. can someone takeover..

**Comment by hatyi** [comment]
Hi I'm also getting the Garnish is not defined error.

**Comment by wmdhosting** [comment]
WHat is status of this ..plugin and future..

I bougth plugin some years ago.  spent quite time and money customising it
And then some bugs prevented me from using it.. 

And then no body respond for year and half now..

**Comment by Edsardio** [comment]
Hi @wmdhosting ,

Due to one of our developers leaving we lost vision on the plugin. 
We plan on maintaining the plugin if a bug comes along and updating the plugin whenever necessary.

If you have any outstanding questions we could help you with let us know!
