### ISSUE TITLE
Adding jQuery link at the bottom of the page

### ISSUE THREAD

**Issue by prashant9841** [creativeorange/craft-article#22]
After upgrading to craft 4 and the plugin version to 2.0.1, there are three links to JavaScript. One of them is jQuery causing it to load twice and causing errors.  I've attached a screenshot for reference. Please Help.

![image](https://user-images.githubusercontent.com/20434756/222293696-dc50b11a-6a41-48c4-a724-7ac528bc460c.png)

**Comment by felixschwan** [comment]
Hi, on my Craft CMS v4 website the plugin is still loading jQuery via `my-site.com/cpresources/72f6d8a1/jquery.js`.
Causing issues with my custom loaded jQuery and app.js code.

Is there any possibility to deactivate auto-loading jQuery?
(Don't want to change code in the `vendor/creativeorange/craft-article/src/assets/EditorAssets.php` nor want to write a custom-module to override the init() function there).
