### ISSUE TITLE
Plugins do not load

### ISSUE THREAD

**Issue by bryanredeagle** [creativeorange/craft-article#26]
When I add plugins to the config, they do not load. In fact, none of the plugins other than the custom craft plugins load. Here is my definition with my config:
```
"plugins": [
        "craft-image",
        "craft-image-editor",
        "craft-link",
        "imageposition",
        "reorder",
        "underline",
        "removeformat",
        "selector",
        "blockcode",
        "inlineformat",
        "fontcolor",
        "imageresize"
],
```

I attempted to download the plugins and place them in the `/web/article` folder, but they still did not load. Any suggestions?

I am running v3.0.0 on Craft 4.7.1.

Thanks!

**Comment by Edsardio** [comment]
Hi @bryanredeagle 

I've just created version v3.1.0 which should fix this issue.
If you have any other questions please let us know!
