### ISSUE TITLE
Craft 5.0.0 Support

### ISSUE THREAD

**Issue by MatthewBUK** [creativeorange/craft-article#29]
Hi, 

As Craft CMS has launched its version 5 this version of the plugin is not compatible currently. Is there going to be an update to this plugin ? (We are/where a licensed user via the Craft CMS store)

Thank you

**Comment by Edsardio** [comment]
Hi @MatthewBUK 

Sorry for my late reply, we're currently working on an update to support craft 5.0.0.
I'll keep you updated in this issue once it releases.

**Comment by Edsardio** [comment]
As of version v5.0.0 there is now craft support. Apologies for the long delay
