### ISSUE TITLE
Imperavi Article license?

### ISSUE THREAD

**Issue by khalwat** [creativeorange/craft-article#5]
Does this plugin's purchase price include a license to [Imperavi's Article](https://imperavi.com/article/) product?

The license appears to be [$699](https://imperavi.com/article/buy/) -- I ask because the [license restrictions](https://imperavi.com/article/license/) make me concerned there could be an issue:

.....

**Restrictions** 

Unless you have been granted prior, written explicit consent from Imperavi LLC, you may not:

- Use the Software in Open Source projects.
- Reproduce, distribute, or transfer the Software as a sole product, or portions thereof, to any third party.
- Sell, rent, lease, assign, or sublet the Software as a sole product or portions thereof.
- Grant rights to any other person.
- Use the software in violation of any European Union or international laws or regulations.

**Comment by RobinWissink** [comment]
@khalwat 

Hi Andrew, 

Thanks for your comment. 

During development of the plugin, we have been in close contact with Imperavi about their license. We have:
1. Written confirmation that buyers of the Craft Plugin do not need to purchase a license from Imperavi  themselves.
2. We comply with the terms of the license by loading the Article Editor source code from a CDN.

Finally, before adding the plugin to the Craft Plugin Store, we shared the plugin with Imperavi. Subsequently, we received the green light to publish the plugin.

Hope you enjoy the plugin :)

**Comment by khalwat** [comment]
Awesome! Might be helpful to include this licensing information in the documentation.
