### ISSUE TITLE
Images not getting parsed URL

### ISSUE THREAD

**Issue by peirix** [creativeorange/craft-article#6]
I have a fresh Craft install with only this plugin loaded, and in there the images are not being parsed with the correct URLs

![image](https://user-images.githubusercontent.com/347175/130225975-f0b4a01a-f19f-4800-a676-8a52babde40c.png)

Is this something to set up in a config somewhere?

**Comment by jacotijssen** [comment]
Hi @peirix!

Thanks for taking your time submitting an issue! 

Do you have the option "Assets in this volume have public URLs" (asset source settings in `admin/settings/assets`) enabled and did you correctly configure the base URL for this asset volume?

For more info, see [https://craftcms.com/docs/3.x/assets.html#volumes](https://craftcms.com/docs/3.x/assets.html#volumes)

Look forward hearing from you!

**Comment by peirix** [comment]
Hi, yes. I've set the public URL, using an alias `@web/bilder` Don't know if that has anything to say. But checking it again now, I got one step closer, getting this:

![image](https://user-images.githubusercontent.com/347175/130418854-5e6b0578-5aee-4afd-97a3-372c8bb1cd3e.png)

**Comment by dejury** [comment]
Hi @peirix,

Did you actually change the settings after our suggestion? If this is the case, do you have the same issue when you create a new entry?

**Comment by peirix** [comment]
Hi. I went in and resaved the assets config, trying both to hardcode the url and using the alias. But still getting the same issue, even with new entries.

**Comment by peirix** [comment]
I even deleted the asset config, made a new one (with a new name), and getting the same issue. The image is showing correctly in the wysiwig, but not in the template.

**Comment by dejury** [comment]
@peirix Thanks for checking it! Can you please send me a screenshot of the fieldvalue in your database (the one you are trying to print on the frontend)?

**Comment by peirix** [comment]
@dejury Do you mean from the `craft_content` table?

![image](https://user-images.githubusercontent.com/347175/130918337-576fbc6e-3905-4621-ab79-7e80e280df30.png)

**Comment by peirix** [comment]
Just went in to check again, and when I add an image, it shows up correctly in the wysiwig, but then if I save and go back to the entry list, and then go back into the entry again, the image is no longer showing, and the URL is as I showed above.

**Comment by dejury** [comment]
@peirix I can't reproduce this issue, even with the exact same value in the field. Can you provide me with the details shown on the CraftCMS page "Utilities > System Report". Maybe this is a specific CraftCMS version issue.

**Comment by peirix** [comment]
Okay, so I had a bad feeling about this, and ended up just deleting the whole installation and starting over, and now it works. So I'm not sure where in the process I managed to screw this up, but maybe because I installed the plugin before adding any assets or sections? Not sure. Sorry to steal your time on this :/

**Comment by dejury** [comment]
I’m glad you have a working plugin now. In a meantime, we’re going to test our plugin with this scenario in mind, so any future users won’t have to experience the same issue. Thanks for your time and patience. If I can help or assist you with any other questions, I am happy to help you!
