### ISSUE TITLE
Postgres Error

### ISSUE THREAD

**Issue by theskyfloor** [creativeorange/craft-article#7]
```SQLSTATE[42704]: Undefined object: 7 ERROR: type "mediumtext" does not exist at character 52
The SQL being executed was: ALTER TABLE "content" ADD "field_article_vygolump" mediumtext
Error Info: Array
(
    [0] => 42704
    [1] => 7
    [2] => ERROR:  type "mediumtext" does not exist at character 52
)
↵
Caused by: PDOException

SQLSTATE[42704]: Undefined object: 7 ERROR: type "mediumtext" does not exist at character 52

in /home/forge/site/vendor/yiisoft/yii2/db/Command.php at line 1302

**Comment by jacotijssen** [comment]
Hi @theskyfloor!

Thank you for reaching out and trying our brand new plugin! I'll take a look at it and will get back to you within a few hours.

**Comment by jacotijssen** [comment]
Hello again @theskyfloor,

It seems the plugin isn't fully compatible with PostgreSQL yet. I'll fix this pesky bug and test the plugin thoroughly with PostgresSQL this weekend and get back to you.

Thank you for your patience!

**Comment by theskyfloor** [comment]
Thanks! Excited to try it out.

**Comment by jacotijssen** [comment]
Hi @theskyfloor!

I've tagged a new version (v1.0.3) which will fix the PostgreSQL error.
