### ISSUE TITLE
Flash of unstyled content

### ISSUE THREAD

**Issue by piotrpog** [creativeorange/craft-article#8]
When element page with article field loads, we briefly see textarea before JS loads and article editor initializes.

**Comment by dejury** [comment]
Hi @piotrpog 

Thanks for your feedback, since we are using a CDN to load the javascript (due to licensing restrictions) we are not entirely sure if we can fix this. We will keep this in mind for a future update, for now I will close the issue!

**Comment by piotrpog** [comment]
@dejury 
maybe article emits some event when it is initialized? So until then, textarea could be just hidden by display: none

**Comment by dejury** [comment]
> @dejury
> maybe article emits some event when it is initialized? So until then, textarea could be just hidden by display: none

Good suggestion, will have a look at this shortly.
