### ISSUE TITLE
Composer conflict with Guzzle

### ISSUE THREAD

**Issue by AndrewMac** [creativeorange/craft-article#9]
Hi there, and sorry I'm in such a rush. This plugin looked really interesting, but I can't get it installed. There are quite a few composer conflicts because of plugins that are restricted to guzzle 6.x.x, and Article requires 7.

Any suggestions on what to do about this? Can Article work with earlier guzzle versions? I've seen some plugins use a requirement like guzzle: ^6.5|^7.0 (for example).

Cheers, Andrew

**Comment by jacotijssen** [comment]
Hi @AndrewMac,

Thanks for reporting the issue, we'll take a look at it and get back to you within the next hour.

Cheers, Jaco

**Comment by jacotijssen** [comment]
We've just released v1.0.4, which will fix this issue. Thanks for reporting!
